package com.wcs.newsletter.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the EmailTemplate service. Represents a row in the &quot;WcsNewsletter_EmailTemplate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.wcs.newsletter.model.impl.EmailTemplateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.wcs.newsletter.model.impl.EmailTemplateImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmailTemplate
 * @see com.wcs.newsletter.model.impl.EmailTemplateImpl
 * @see com.wcs.newsletter.model.impl.EmailTemplateModelImpl
 * @generated
 */
public interface EmailTemplateModel extends BaseModel<EmailTemplate> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a email template model instance should use the {@link EmailTemplate} interface instead.
     */

    /**
     * Returns the primary key of this email template.
     *
     * @return the primary key of this email template
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this email template.
     *
     * @param primaryKey the primary key of this email template
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the email template ID of this email template.
     *
     * @return the email template ID of this email template
     */
    public long getEmailTemplateId();

    /**
     * Sets the email template ID of this email template.
     *
     * @param emailTemplateId the email template ID of this email template
     */
    public void setEmailTemplateId(long emailTemplateId);

    /**
     * Returns the file entry ID of this email template.
     *
     * @return the file entry ID of this email template
     */
    public long getFileEntryId();

    /**
     * Sets the file entry ID of this email template.
     *
     * @param fileEntryId the file entry ID of this email template
     */
    public void setFileEntryId(long fileEntryId);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(EmailTemplate emailTemplate);

    public int hashCode();

    public CacheModel<EmailTemplate> toCacheModel();

    public EmailTemplate toEscapedModel();

    public String toString();

    public String toXmlString();
}
