package com.wcs.newsletter.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Label service. Represents a row in the &quot;WcsNewsletter_Label&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.wcs.newsletter.model.impl.LabelModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.wcs.newsletter.model.impl.LabelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Label
 * @see com.wcs.newsletter.model.impl.LabelImpl
 * @see com.wcs.newsletter.model.impl.LabelModelImpl
 * @generated
 */
public interface LabelModel extends BaseModel<Label> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a label model instance should use the {@link Label} interface instead.
     */

    /**
     * Returns the primary key of this label.
     *
     * @return the primary key of this label
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this label.
     *
     * @param primaryKey the primary key of this label
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the label ID of this label.
     *
     * @return the label ID of this label
     */
    public long getLabelId();

    /**
     * Sets the label ID of this label.
     *
     * @param labelId the label ID of this label
     */
    public void setLabelId(long labelId);

    /**
     * Returns the tag ID of this label.
     *
     * @return the tag ID of this label
     */
    public long getTagId();

    /**
     * Sets the tag ID of this label.
     *
     * @param tagId the tag ID of this label
     */
    public void setTagId(long tagId);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(Label label);

    public int hashCode();

    public CacheModel<Label> toCacheModel();

    public Label toEscapedModel();

    public String toString();

    public String toXmlString();
}
