package com.wcs.newsletter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the NewsletterConfig service. Represents a row in the &quot;WcsNewsletter_NewsletterConfig&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.wcs.newsletter.model.impl.NewsletterConfigModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.wcs.newsletter.model.impl.NewsletterConfigImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NewsletterConfig
 * @see com.wcs.newsletter.model.impl.NewsletterConfigImpl
 * @see com.wcs.newsletter.model.impl.NewsletterConfigModelImpl
 * @generated
 */
public interface NewsletterConfigModel extends BaseModel<NewsletterConfig> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a newsletter config model instance should use the {@link NewsletterConfig} interface instead.
     */

    /**
     * Returns the primary key of this newsletter config.
     *
     * @return the primary key of this newsletter config
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this newsletter config.
     *
     * @param primaryKey the primary key of this newsletter config
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the config ID of this newsletter config.
     *
     * @return the config ID of this newsletter config
     */
    public long getConfigId();

    /**
     * Sets the config ID of this newsletter config.
     *
     * @param configId the config ID of this newsletter config
     */
    public void setConfigId(long configId);

    /**
     * Returns the config key of this newsletter config.
     *
     * @return the config key of this newsletter config
     */
    @AutoEscape
    public String getConfigKey();

    /**
     * Sets the config key of this newsletter config.
     *
     * @param configKey the config key of this newsletter config
     */
    public void setConfigKey(String configKey);

    /**
     * Returns the config value of this newsletter config.
     *
     * @return the config value of this newsletter config
     */
    @AutoEscape
    public String getConfigValue();

    /**
     * Sets the config value of this newsletter config.
     *
     * @param configValue the config value of this newsletter config
     */
    public void setConfigValue(String configValue);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(NewsletterConfig newsletterConfig);

    public int hashCode();

    public CacheModel<NewsletterConfig> toCacheModel();

    public NewsletterConfig toEscapedModel();

    public String toString();

    public String toXmlString();
}
