package com.wcs.newsletter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Recipient service. Represents a row in the &quot;WcsNewsletter_Recipient&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.wcs.newsletter.model.impl.RecipientModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.wcs.newsletter.model.impl.RecipientImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Recipient
 * @see com.wcs.newsletter.model.impl.RecipientImpl
 * @see com.wcs.newsletter.model.impl.RecipientModelImpl
 * @generated
 */
public interface RecipientModel extends BaseModel<Recipient> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a recipient model instance should use the {@link Recipient} interface instead.
     */

    /**
     * Returns the primary key of this recipient.
     *
     * @return the primary key of this recipient
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this recipient.
     *
     * @param primaryKey the primary key of this recipient
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the recipient ID of this recipient.
     *
     * @return the recipient ID of this recipient
     */
    public long getRecipientId();

    /**
     * Sets the recipient ID of this recipient.
     *
     * @param recipientId the recipient ID of this recipient
     */
    public void setRecipientId(long recipientId);

    /**
     * Returns the newsletter ID of this recipient.
     *
     * @return the newsletter ID of this recipient
     */
    public long getNewsletterId();

    /**
     * Sets the newsletter ID of this recipient.
     *
     * @param newsletterId the newsletter ID of this recipient
     */
    public void setNewsletterId(long newsletterId);

    /**
     * Returns the email of this recipient.
     *
     * @return the email of this recipient
     */
    @AutoEscape
    public String getEmail();

    /**
     * Sets the email of this recipient.
     *
     * @param email the email of this recipient
     */
    public void setEmail(String email);

    /**
     * Returns the status of this recipient.
     *
     * @return the status of this recipient
     */
    @AutoEscape
    public String getStatus();

    /**
     * Sets the status of this recipient.
     *
     * @param status the status of this recipient
     */
    public void setStatus(String status);

    /**
     * Returns the error message of this recipient.
     *
     * @return the error message of this recipient
     */
    @AutoEscape
    public String getErrorMessage();

    /**
     * Sets the error message of this recipient.
     *
     * @param errorMessage the error message of this recipient
     */
    public void setErrorMessage(String errorMessage);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(Recipient recipient);

    public int hashCode();

    public CacheModel<Recipient> toCacheModel();

    public Recipient toEscapedModel();

    public String toString();

    public String toXmlString();
}
