package com.wcs.newsletter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Subscription service. Represents a row in the &quot;WcsNewsletter_Subscription&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.wcs.newsletter.model.impl.SubscriptionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.wcs.newsletter.model.impl.SubscriptionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Subscription
 * @see com.wcs.newsletter.model.impl.SubscriptionImpl
 * @see com.wcs.newsletter.model.impl.SubscriptionModelImpl
 * @generated
 */
public interface SubscriptionModel extends BaseModel<Subscription> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a subscription model instance should use the {@link Subscription} interface instead.
     */

    /**
     * Returns the primary key of this subscription.
     *
     * @return the primary key of this subscription
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this subscription.
     *
     * @param primaryKey the primary key of this subscription
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the subscription ID of this subscription.
     *
     * @return the subscription ID of this subscription
     */
    public long getSubscriptionId();

    /**
     * Sets the subscription ID of this subscription.
     *
     * @param subscriptionId the subscription ID of this subscription
     */
    public void setSubscriptionId(long subscriptionId);

    /**
     * Returns the user ID of this subscription.
     *
     * @return the user ID of this subscription
     */
    public long getUserId();

    /**
     * Sets the user ID of this subscription.
     *
     * @param userId the user ID of this subscription
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this subscription.
     *
     * @return the user uuid of this subscription
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this subscription.
     *
     * @param userUuid the user uuid of this subscription
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the email of this subscription.
     *
     * @return the email of this subscription
     */
    @AutoEscape
    public String getEmail();

    /**
     * Sets the email of this subscription.
     *
     * @param email the email of this subscription
     */
    public void setEmail(String email);

    /**
     * Returns the subscription date of this subscription.
     *
     * @return the subscription date of this subscription
     */
    public Date getSubscriptionDate();

    /**
     * Sets the subscription date of this subscription.
     *
     * @param subscriptionDate the subscription date of this subscription
     */
    public void setSubscriptionDate(Date subscriptionDate);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(Subscription subscription);

    public int hashCode();

    public CacheModel<Subscription> toCacheModel();

    public Subscription toEscapedModel();

    public String toString();

    public String toXmlString();
}
