package com.wcs.newsletter.model;

/*
 * #%L
 * Webstar Newsletter
 * %%
 * Copyright (C) 2013 Webstar Csoport Kft.
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the 
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public 
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/gpl-3.0.html>.
 * #L%
 */

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Label service. Represents a row in the &quot;WcsNewsletter_Label&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.wcs.newsletter.model.impl.LabelModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.wcs.newsletter.model.impl.LabelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Label
 * @see com.wcs.newsletter.model.impl.LabelImpl
 * @see com.wcs.newsletter.model.impl.LabelModelImpl
 * @generated
 */
public interface LabelModel extends BaseModel<Label> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a label model instance should use the {@link Label} interface instead.
     */

    /**
     * Returns the primary key of this label.
     *
     * @return the primary key of this label
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this label.
     *
     * @param primaryKey the primary key of this label
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the label ID of this label.
     *
     * @return the label ID of this label
     */
    public long getLabelId();

    /**
     * Sets the label ID of this label.
     *
     * @param labelId the label ID of this label
     */
    public void setLabelId(long labelId);

    /**
     * Returns the tag ID of this label.
     *
     * @return the tag ID of this label
     */
    public long getTagId();

    /**
     * Sets the tag ID of this label.
     *
     * @param tagId the tag ID of this label
     */
    public void setTagId(long tagId);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(Label label);

    public int hashCode();

    public CacheModel<Label> toCacheModel();

    public Label toEscapedModel();

    public String toString();

    public String toXmlString();
}
